export interface UpdateNote { version:string; date:string; title:string; changes:string[] }

// Every player-facing content/gameplay update must add a dated entry here and in docs/CHANGELOG.md.
export const UPDATES: UpdateNote[] = [
 {version:'0.18.2',date:'2026-10-06',title:'Tree species and project audit',changes:['Falling frames now match broadleaf, pine or date palm based on the actual standing tree sprite.','Attack-move orders can finish at their closest reachable endpoint instead of looping forever.','Added a detailed audit of remaining art, animation, movement and performance gaps.']},
 {version:'0.18.1',date:'2026-10-05',title:'Woodcutting actually works',changes:['Workers can stop at the walkable ring around a blocked tree and perform axe cycles.','Each hit deepens a visible trunk notch and throws wood chips before the six-pose fall.','A fallen tree stays a collectible log after the animation instead of reappearing upright; it becomes a stump after depletion.','Other assets still need consistency and browser visual review.']},
 {version:'0.18.0',date:'2026-10-05',title:'Chopped-tree animation and path clearance',changes:['Villager chopping now uses six falling poses for oak and pine, followed by collectible logs and then a stump. Tree sway rises with chop progress.','Terrain depth includes elevation and sprite-row height, so upper crowns remain visible while raised foreground terrain can occlude the lower trunk.','Path search accounts for unit footprint when passing blocked-cell gaps. Enemy AI scores visible targets by route reachability and distance.','Tree frame atlas is original generated art; walking animation source remains the existing eight-pose atlas. Browser performance and visual acceptance remain pending.']},
 {version:'0.17.0',date:'2026-10-05',title:'Authored construction stages and reachable routes',changes:['Added a new 16-sprite construction atlas: four real stages across house, hall, civic and fortress families; the same stages are used for building and renovations.','Routing now explores the whole map and follows the closest reachable endpoint when a commanded location is blocked. Direct arrival is only accepted if the straight approach is clear.','Build sprites are original generated art. The four structure families are shared across specific buildings; faction and age variations are not yet separately illustrated.']},
 {version:'0.16.1',date:'2026-10-05',title:'Woodland ground',changes:['Layered transparent soil patches blend tree bases into existing terrain.','Added leaf litter, pine needles and sparse existing ground-cover sprites around trees.','Ground cover hides beneath newly placed buildings. No new shrub artwork was generated.']},
 {version:'0.16.0',date:'2026-10-05',title:'Terrain depth and traffic',changes:['Foreground terrain now clips sprites using world depth.','Blocked routes can retry around stationary units; stopping preserves gait pose.','Field soil edges are softened. Browser visual acceptance and source-art refinement remain pending.']},
 {version:'0.15.4',date:'2026-10-05',title:'Movement clearance',changes:['Routes account for unit clearance and avoid unsafe exact endpoints.','Units face sharp turns before moving; reduced settlement ground halos and added grounded perimeter detail.','Existing animation artwork and crowded traffic still need further refinement.']},
 {version:'0.15.3',date:'2026-10-05',title:'Growing wheat height',changes:['Wheat height now grows independently of plot width and stays anchored to the soil.','Existing crop artwork is rescaled; visual review remains pending.']},
 {version:'0.15.2',date:'2026-10-05',title:'Terrain and stable structures',changes:['Stable sprite ordering and persistent explored building visibility.','Building placement rejects uneven footprints, cliff samples and water. Existing structures stay in place.','Stronger terrain slope shading; full foreground terrain occlusion remains pending.']},
  {version:'0.15.1',date:'2026-10-05',title:'Working fields',changes:['Fields can be selected by their ground footprint, and assigned an idle farmer.','Farm builders continue tending crops; plants and workers share world depth.','Replaced flat scaffolds with projected faces and reduced oversized ground shadows. Generated source artwork still needs visual refinement.']},
  {version:'0.15.0',date:'2026-10-05',title:'Builders and fortifications',changes:['Villagers now perform age renovations and fortification upgrades; use Repair to assign workers. Existing damage is repaired first.','Drag walls and palisades to queue contiguous sections. Existing matching wall segments are skipped when extending a route.','Added Watchtower, Archer Tower and Cannon Tower, aimed attacks and cannon recoil; base tower art remains shared.','Added resource blockers, local unit separation, stone paving, coastal fish and reeds, and regional palms and pines. No new inland river or coconut-specific art yet.','Construction and falling-tree motion remain composed from existing sprites. Visual acceptance is still pending.']},
  {version:'0.14.0',date:'2026-10-05',title:'Construction frame sequence',changes:['Each active building facade now renders through sixteen cached construction frames, with neighboring frames blended as work progresses.','Frame artwork is baked on demand from the selected Roman/Persian age and facing sprite; the cache is bounded to keep memory use modest.','Foundation, masonry, roof, and scaffold stages are present in the frames; scaffolds fade out before completion.','Hammer glints occur only at active builders and follow the existing four-pose worker action cycle. Frames are programmatically composed from the existing artwork, not sixteen separately illustrated source images.']},
  {version:'0.13.0',date:'2026-10-05',title:'Construction phases',changes:['Unfinished buildings now reveal upward from the foundation through five construction phases instead of fading in as complete structures.','Timber scaffolds gain posts and cross-bracing as progress advances; delivered materials and rhythmic hammer impacts animate around the active structure.','The facade sprite used during construction follows the player’s current Roman/Persian age and building facing.','No browser visual acceptance; phase timing and scaffold overlap remain unreviewed in play.']},
  {version:'0.12.0',date:'2026-10-05',title:'Age-specific settlements and living fields',changes:['Added original Roman and Persian Dark, Feudal and Imperial architecture sprite views for twelve settlement buildings, each with four facings; Castle Age retains the existing castle-era facade set. Artwork for the active age loads on demand.','Added visible field growth stages from bare tilled ground through green crop to ripe wheat. Farmers move to individual plots and are sorted between crop sprites; orchard plots regrow fruit.','Added four-direction gold and stone seams at three depletion states, sparse wild grasses and more varied tree-fall projection.','No new gameplay test or browser visual review; generated artwork and directional matches remain approximate.']},
  {version:'0.11.0',date:'2026-10-04',title:'Settlement renewal',changes:['Replaced upright building art with Roman/Persian facade views, including fortifications and production camps. Press R to rotate placement or a selected structure.','Added continuous terrain shading, a western ravine, cliff rocks, region-based woodland and layered coastal water.','Added staged building damage, animated fire/smoke, collapsing sections and persistent rubble.','Fixed sprite crops and grounded building foundations; saves retain facing.','Generated facade consistency and in-game visual acceptance remain unfinished.']},
  {version:'0.10.0',date:'2026-10-04',title:'Elephants and chariots',changes:['Dedicated walking and attack atlases replace the horse placeholders for Persian war elephants and royal chariots.','Adjusted elephant/chariot visual scale, stride, turning speed and chariot spacing.','Stable training uses the actual queued unit art.','Measured sprite row boundaries and excluded the malformed elephant walking east row.','Generated anatomical and frame-continuity limitations remain.']},
  {version:'0.9.0',date:'2026-10-04',title:'Mounted armies',changes:['Added eight-pose camel lancer, camel swordsman and horse archer attack atlases.','Added bow-equipped horse archer and sword-equipped camel walking art.','Shared strike/animation release time and raised projectile launch points with terrain-independent arcs.','Added alpha-aware combat sprite picking and queue-matched mounted training art.','Generated anatomy, direction accuracy and frame continuity remain in production.']},
  {version:'0.8.1',date:'2026-10-03',title:'Movement continuity',changes:['Bounded turn steering, arrival braking and stable passing preferences.','Interpolated effect and projectile time, with arrow orientation following the flight arc.','Work animations wait for the unit to settle; unsupported mounted attack types retain their mount.','Animated shore ripples. Dedicated camel and mounted-archer attack art remains pending.']},
  {version:'0.8.0',date:'2026-10-03',title:'Walking and terrain',changes:['Six new walking atlases with eight samples per heading and registered torso pivots.','Interpolated unit positions between simulation steps, distance-driven gait and limited turn speed.','Blended grass, dry soil, track and limestone materials, irregular woodland distribution and scalloped ridge outlines.','Generated gait continuity, mirrored equipment and shared unit art still require refinement.']},
  {version:'0.7.0',date:'2026-10-03',title:'Working settlements',changes:['Added directional attack poses for seven combat families.','Added roads built and queued by villagers.','Added council, university, temple healing and tool repair at a blacksmith.','Added windmill, delivery processing and queue-driven military training animations.','Added woodland ground cover. Generated animation continuity and full unique-unit coverage remain unfinished.']},
  {version:'0.6.0',date:'2026-10-03',title:'Living terrain and economy',changes:['Raised terrain, cliff navigation and routed roads.','Worker job cycles, trees falling into timber and stumps, ore depletion, berry picking and crop growth.','Distinct production buildings, garrison entry and siege action poses.','Directional walking, cavalry scale, pathfinding, camera and object picking improvements. Animation and roster art remain in production.']},
  {version:'0.2.0',date:'2026-10-02',title:'Civilization foundations',changes:[
    'Added four historically framed civilization profiles with distinct architecture, economy, military identity, landmark and unique-unit rosters.',
    'Added a shared unit catalogue with era unlocks, costs, combat stats, armour classes and counter guidance.',
    'Added structure and landmark definitions for the content browser.',
    'Added in-game civilization and roster inspection panel; historical scope notes are visible with each civilization.'
  ]},
  {version:'0.1.0',date:'2026-10-02',title:'3D browser prototype',changes:[
    'Introduced the WebGL battlefield, camera, basic resource HUD, selection, movement and early economy interactions.'
  ]}
];
