import * as T from 'three';
import {GLTFLoader,type GLTF} from 'three/addons/loaders/GLTFLoader.js';
import {BUILDINGS,FACTIONS,UNITS} from './data';
import {World,type Entity,type Point} from './world';
import {treeModel,surfaceTexture,terrainTexture} from './environment';
interface Actor {root:T.Group;model?:T.Object3D;mixer?:T.AnimationMixer;clips?:T.AnimationClip[];action?:T.AnimationAction;state:string;ring:T.Mesh;bar:T.Mesh;lastTier:number;}
export class Battlefield {
 scene=new T.Scene();renderer:T.WebGLRenderer;camera=new T.PerspectiveCamera(43,1,.1,250);focus=new T.Vector3(-28,0,-20);distance=42;azimuth=.5;elevation=.88;actors=new Map<number,Actor>();cache=new Map<string,Promise<GLTF>>();loader=new GLTFLoader();ray=new T.Raycaster();pointer=new T.Vector2();groundPlane=new T.Plane(new T.Vector3(0,1,0),0);selected=new Set<number>();world:World;canvas:HTMLCanvasElement;placement:T.Mesh;projectiles=new Map<number,T.Mesh>();fog:T.Mesh;fogTexture:T.CanvasTexture;fogCanvas=document.createElement('canvas');fowTimer=0;materialCache=new Map<string,T.Material>();
 constructor(host:HTMLElement,world:World){this.world=world;this.renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance'});this.canvas=this.renderer.domElement;host.append(this.canvas);this.renderer.setPixelRatio(Math.min(devicePixelRatio,1.25));this.renderer.shadowMap.enabled=true;this.renderer.shadowMap.type=T.PCFSoftShadowMap;this.renderer.toneMapping=T.ACESFilmicToneMapping;this.renderer.toneMappingExposure=1.0;this.scene.background=new T.Color('#abb4b0');this.scene.fog=new T.Fog('#abb4b0',100,200);this.scene.add(new T.HemisphereLight(0xf9edcd,0x50674b,1.35));const sun=new T.DirectionalLight(0xffedcb,2.5);sun.position.set(-38,60,-30);sun.castShadow=true;sun.shadow.mapSize.set(2048,2048);Object.assign(sun.shadow.camera,{left:-70,right:70,top:70,bottom:-70,far:160});sun.shadow.bias=-.001;this.scene.add(sun);
 const texture=terrainTexture();const ground=new T.Mesh(new T.PlaneGeometry(132,132),new T.MeshStandardMaterial({map:texture,roughness:1}));ground.rotation.x=-Math.PI/2;ground.receiveShadow=true;this.scene.add(ground);
 const road=new T.Mesh(new T.PlaneGeometry(105,3.2),new T.MeshStandardMaterial({color:'#a09476',roughness:1}));road.rotation.x=-Math.PI/2;road.rotation.z=-.63;road.position.set(0,.012,0);this.scene.add(road);
 this.placement=new T.Mesh(new T.CylinderGeometry(3,3,.05,32),new T.MeshBasicMaterial({color:'#b7ce93',transparent:true,opacity:.4}));this.placement.visible=false;this.scene.add(this.placement);
 this.fogCanvas.width=this.fogCanvas.height=64;this.fogTexture=new T.CanvasTexture(this.fogCanvas);this.fogTexture.magFilter=T.LinearFilter;this.fog=new T.Mesh(new T.PlaneGeometry(128,128),new T.MeshBasicMaterial({map:this.fogTexture,transparent:true,depthWrite:false}));this.fog.rotation.x=-Math.PI/2;this.fog.position.y=.06;this.fog.renderOrder=4;this.scene.add(this.fog);
 new ResizeObserver(()=>{this.renderer.setSize(host.clientWidth,host.clientHeight);this.camera.aspect=host.clientWidth/host.clientHeight;this.camera.updateProjectionMatrix();}).observe(host);this.positionCamera();}
 setWorld(world:World){this.world=world;for(const a of this.actors.values()){a.mixer?.stopAllAction();this.scene.remove(a.root);}this.actors.clear();for(const p of this.projectiles.values())this.scene.remove(p);this.projectiles.clear();this.selected.clear();this.focus.set(-28,0,-20);this.positionCamera();}
 positionCamera(){this.focus.x=T.MathUtils.clamp(this.focus.x,-57,57);this.focus.z=T.MathUtils.clamp(this.focus.z,-57,57);this.camera.position.set(this.focus.x+Math.sin(this.azimuth)*Math.cos(this.elevation)*this.distance,Math.sin(this.elevation)*this.distance,this.focus.z+Math.cos(this.azimuth)*Math.cos(this.elevation)*this.distance);this.camera.lookAt(this.focus);}
 pan(dx:number,dz:number){this.focus.x+=Math.cos(this.azimuth)*dx+Math.sin(this.azimuth)*dz;this.focus.z+=-Math.sin(this.azimuth)*dx+Math.cos(this.azimuth)*dz;this.positionCamera();}
 zoom(d:number){this.distance=T.MathUtils.clamp(this.distance+d,9,95);this.positionCamera();}
 groundPoint(clientX:number,clientY:number):Point|null{const b=this.canvas.getBoundingClientRect();this.pointer.set((clientX-b.left)/b.width*2-1,-(clientY-b.top)/b.height*2+1);this.ray.setFromCamera(this.pointer,this.camera);const p=new T.Vector3();return this.ray.ray.intersectPlane(this.groundPlane,p)?{x:p.x,z:p.z}:null;}
 pick(x:number,y:number){this.groundPoint(x,y);const objects=[...this.actors.values()].filter(a=>a.root.visible).map(a=>a.root);const hit=this.ray.intersectObjects(objects,true).find(h=>!h.object.userData.ui);if(!hit)return;let o:T.Object3D|null=hit.object;while(o&&!o.userData.entity)o=o.parent;return o?this.world.get(o.userData.entity):undefined;}
 private resourceModel(e:Entity){const root=new T.Group();if(e.def==='wood'){return treeModel(e.id);}else if(e.resource==='food'){for(let i=0;i<4;i++){const shrub=new T.Mesh(new T.SphereGeometry(.6,12,8),new T.MeshStandardMaterial({color:'#6b7749'}));shrub.position.set(Math.sin(i*2)*.6,.5,Math.cos(i*2)*.6);root.add(shrub);for(let k=0;k<3;k++){const berry=new T.Mesh(new T.SphereGeometry(.09,7,6),new T.MeshStandardMaterial({color:'#925349'}));berry.position.set(shrub.position.x+.3,.7+k*.09,shrub.position.z+.35);root.add(berry);}}}else for(let i=0;i<5;i++){const stone=new T.Mesh(new T.DodecahedronGeometry(.6+i*.08,1),new T.MeshStandardMaterial({color:e.resource==='gold'?'#ac9361':'#8a8981',roughness:.85}));stone.position.set(Math.sin(i*2)*.8,.3,Math.cos(i*2)*.8);stone.scale.y=.7;root.add(stone);}root.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;}});return root;}
 asset(id:string){if(!this.cache.has(id))this.cache.set(id,this.loader.loadAsync(`/assets/3d/generated/${id}.glb`));return this.cache.get(id)!;}
 async preload(progress:(n:number,total:number)=>void){const keys=[...new Set(this.world.entities.filter(e=>e.type!=='resource').map(e=>e.type==='building'?'b-'+e.def+(e.owner<2?'-'+this.world.players[e.owner].faction:''):e.def))];let done=0;await Promise.all(keys.map(async id=>{await this.asset(id);progress(++done,keys.length);}));}
 actor(e:Entity){const root=new T.Group();root.userData.entity=e.id;this.scene.add(root);const ring=new T.Mesh(new T.RingGeometry(this.world.footprint(e)+.25,this.world.footprint(e)+.34,40),new T.MeshBasicMaterial({color:e.owner===0?'#cfdaa4':'#ec8a70',side:T.DoubleSide}));ring.rotation.x=-Math.PI/2;ring.position.y=.09;ring.userData.ui=true;root.add(ring);const bar=new T.Mesh(new T.PlaneGeometry(e.type==='building'?3:1.4,.11),new T.MeshBasicMaterial({color:e.owner===0?'#b4ce86':'#df7565',depthTest:false}));bar.position.y=e.type==='building'?7:e.type==='unit'&&UNITS[e.def].mounted?3.5:2.5;bar.userData.ui=true;bar.renderOrder=6;root.add(bar);const a:Actor={root,ring,bar,state:'',lastTier:1};this.actors.set(e.id,a);
 if(e.type==='resource'){a.model=this.resourceModel(e);root.add(a.model);}else{this.asset(e.type==='building'?'b-'+e.def+(e.owner<2?'-'+this.world.players[e.owner].faction:''):e.def).then(gltf=>{if(this.actors.get(e.id)!==a)return;const model=gltf.scene.clone(true);const faction=e.owner<2?this.world.players[e.owner].faction:'english';model.traverse(o=>{if(o instanceof T.Mesh){o.castShadow=true;o.receiveShadow=true;if(!Array.isArray(o.material)&&['limestone','roof','oak','chainmail','team-cloth'].includes(o.material.name)){const mat=o.material as T.MeshStandardMaterial;if(!mat.map){mat.map=surfaceTexture(mat.name);mat.bumpMap=mat.map;mat.bumpScale=mat.name==='limestone'?.055:.02;mat.needsUpdate=true;}}if(!Array.isArray(o.material)&&o.material.name==='team-cloth'){const key=e.owner+'-'+faction;if(!this.materialCache.has(key)){const material=o.material.clone() as T.MeshStandardMaterial;material.color.set(e.owner===1?'#a04838':FACTIONS[faction].accent);this.materialCache.set(key,material);}o.material=this.materialCache.get(key)!;}}});a.model=model;root.add(model);if(gltf.animations.length){a.mixer=new T.AnimationMixer(model);a.clips=gltf.animations;}},()=>this.world.emit(`Model ${e.def} could not load. Reload the page to retry.`,'error'));}return a;}
 render(dt:number){for(const e of this.world.entities){let a=this.actors.get(e.id);if(!a&&e.hp<=0)continue;if(!a)a=this.actor(e);const visible=e.owner===0||e.type==='resource'?this.world.explored[0].has(Math.floor((e.z+64)/2)*64+Math.floor((e.x+64)/2)):this.world.canSee(0,e);a.root.visible=visible&&!e.inside;if(!a.root.visible)continue;a.root.position.set(e.x,0,e.z);a.root.rotation.y=e.type==='unit'?e.angle:0;a.ring.visible=this.selected.has(e.id)&&e.hp>0;a.bar.visible=(this.selected.has(e.id)||e.hp<e.maxHp)&&e.hp>0&&e.type!=='resource';a.bar.scale.x=Math.max(0,e.hp/e.maxHp);a.bar.quaternion.copy(this.camera.quaternion);a.bar.quaternion.premultiply(a.root.quaternion.clone().invert());
 if(a.model){if(e.type==='building'){a.model.scale.setScalar(.3+e.progress*.7);a.model.position.y=e.hp<=0?-2.2:0;for(const tier of [2,3]){const part=a.model.getObjectByName('fortification'+tier);if(part)part.visible=e.tier>=tier;}const gate=a.model.getObjectByName('gatePanel');if(gate)gate.position.y=e.closed?0:3.7;const rotor=a.model.getObjectByName('rotor');if(rotor)rotor.rotation.z+=dt*.3;}if(e.type==='resource')a.model.scale.y=e.amount<=0?.15:1;const cargo=a.model.getObjectByName('cargo');if(cargo)cargo.scale.setScalar(Object.values(e.cargo).some(v=>v>0)?1:.001);}
 if(a.mixer&&a.clips){let state=e.hp<=0?'death':e.state==='deposit'?'carry':['gather','build','heal','attack','walk'].includes(e.state)?e.state:'idle';if(a.state!==state){const clip=a.clips.find(c=>c.name===state)??a.clips[0];const action=a.mixer.clipAction(clip);action.reset().setLoop(['death','attack'].includes(state)?T.LoopOnce:T.LoopRepeat,['death','attack'].includes(state)?1:Infinity);action.clampWhenFinished=state==='death';action.play();if(a.action)action.crossFadeFrom(a.action,.18,true);a.action=action;a.state=state;}a.mixer.update(dt);}else if(e.hp<=0)a.root.visible=false;}
 for(const s of this.world.shots){let mesh=this.projectiles.get(s.id);if(!mesh){mesh=new T.Mesh(s.splash?new T.SphereGeometry(.2,8,6):new T.CylinderGeometry(.025,.025,.8,5),new T.MeshStandardMaterial({color:s.splash?'#74736a':'#cbb78a'}));this.projectiles.set(s.id,mesh);this.scene.add(mesh);}const t=1-s.remaining/s.duration;mesh.position.set(T.MathUtils.lerp(s.from.x,s.to.x,t),1.5+Math.sin(t*Math.PI)*(s.splash?9:2),T.MathUtils.lerp(s.from.z,s.to.z,t));mesh.visible=this.world.canSee(0,{x:mesh.position.x,z:mesh.position.z});}for(const[id,mesh]of this.projectiles)if(!this.world.shots.some(s=>s.id===id)){this.scene.remove(mesh);mesh.geometry.dispose();(mesh.material as T.Material).dispose();this.projectiles.delete(id);}
 this.fowTimer+=dt;if(this.fowTimer>.3){this.fowTimer=0;const ctx=this.fogCanvas.getContext('2d')!;ctx.clearRect(0,0,64,64);for(let z=0;z<64;z++)for(let x=0;x<64;x++){const i=z*64+x;ctx.fillStyle=this.world.visible[0].has(i)?'#06100800':this.world.explored[0].has(i)?'#07120b66':'#08130de8';ctx.fillRect(x,z,1,1);}this.fogTexture.needsUpdate=true;}
 this.renderer.render(this.scene,this.camera);}
 minimap(canvas:HTMLCanvasElement){const ctx=canvas.getContext('2d')!,size=canvas.width;ctx.fillStyle='#677454';ctx.fillRect(0,0,size,size);for(let z=0;z<64;z++)for(let x=0;x<64;x++){const i=z*64+x;if(!this.world.visible[0].has(i)){ctx.fillStyle=this.world.explored[0].has(i)?'#15271c77':'#081009e8';ctx.fillRect(x/64*size,z/64*size,size/64+1,size/64+1);}}for(const e of this.world.entities){if(e.hp<=0||e.inside||e.type==='resource'||!this.world.canSee(0,e))continue;ctx.fillStyle=e.owner===0?'#a7d7cf':e.owner===1?'#e27558':'#d6ba73';const w=e.type==='building'?5:2;ctx.fillRect((e.x+64)/128*size-w/2,(e.z+64)/128*size-w/2,w,w);}ctx.strokeStyle='#f1dec0';ctx.strokeRect((this.focus.x+64)/128*size-18,(this.focus.z+64)/128*size-12,36,24);}
}
