import {isField,fieldWorkPoint,TREE_FALL_SECONDS} from './field-layout';
import type {VillagerAppearance} from './villager-sprites';
import {ATTACK_WINDUP} from './combat-timing';
import {findPath,invalidatePathCache} from './pathfinding';
import {MAP_SIZE,MAP_HALF,GRID_SIZE,isWater,isCliff,flatSite,worldCell,gridIndex} from './map';
import {AGE_COSTS,AGE_TIMES,BUILDINGS,UNITS,TECHNOLOGIES,emptyStock,type Resource,type Stock,type Cost,type Side,type Faction,type UnitDef} from './data';
export type Point={x:number;z:number};
export type Order={kind:'move'|'attack'|'attackmove'|'gather'|'build'|'repair'|'hold'|'garrison'|'trade'|'repairtools';target?:number;point?:Point;resource?:Resource;gatherOrigin?:Point;groupSpeed?:number;skipped?:{id:number;until:number}[]};
export interface Entity extends Point {id:number;type:'unit'|'building'|'resource';def:string;appearance?:VillagerAppearance;workSite?:{target:number;point:Point;version:number;last:Point;stalled:number;best?:number};workAvoid?:Point;workReplans?:number;workRetryAt?:number;idleSince?:number;unreachable?:number;owner:Side;hp:number;maxHp:number;angle:number;state:string;order?:Order;orders:Order[];cargo:Stock;path:Point[];pathGoal?:Point;pathEnd?:Point;pathVersion:number;timer:number;cooldown:number;progress:number;tier:number;queue:{unit:string;progress:number;reserved:boolean}[];garrison:number[];inside?:number;amount:number;resource?:Resource;closed:boolean;lastHit:number;facing?:number;visualEra?:number;workedAt?:number;renovation?:{progress:number};destroyedAt?:number;research?:{id:string;progress:number};rally?:Point;tradeLeg?:boolean;turn:number;toolCondition?:number;processUntil?:number;processed?:Stock;initialAmount?:number;depletedAt?:number;felledAt?:number;fallAngle?:number;chopProgress?:number;growth?:number;workPhase?:number;enteredAt?:number;entryPoint?:Point;lastAttackAt?:number;moveSpeed?:number;steeringAngle?:number;passingOffset?:number;depositTarget?:number;depositNavVersion?:number;stance?:'line'|'spread'|'testudo';strike?:{target:number;remaining:number};}
export interface Player {faction:Faction;stock:Stock;era:number;armor:number;tools:number;cart:boolean;defeat:number;tech:string[];}
export interface Shot {id:number;owner:Side;from:Point;to:Point;target:number;damage:number;remaining:number;duration:number;splash:number;kind:string;fire?:boolean;launchHeight?:number;targetHeight?:number;}
export type AiLevel='easy'|'normal'|'hard'|'expert';
export type VillagerAI='manual'|'assist'|'auto';
// interval: seconds between AI decisions; gather: enemy gather multiplier; counter: chance to pick a counter unit.
export const AI_LEVELS:Record<AiLevel,{interval:number;workers:number;wave:number;gather:number;counter:number;queue:number}>={
 easy:{interval:9,workers:10,wave:12,gather:.8,counter:0,queue:1},
 normal:{interval:5,workers:18,wave:7,gather:1,counter:0,queue:2},
 hard:{interval:3.5,workers:24,wave:8,gather:1.1,counter:.6,queue:2},
 expert:{interval:2.5,workers:30,wave:10,gather:1.25,counter:.85,queue:3},
};
export interface Snapshot {version:3;mapSize?:number;time:number;nextId:number;rng:number;players:Player[];entities:Entity[];shots:Shot[];explored:number[][];winner:number|null;mode:string;deposited:Stock;aiTimer:number;}
const dist=(a:Point,b:Point)=>Math.hypot(a.x-b.x,a.z-b.z);
const clamp=(x:number,min:number,max:number)=>Math.max(min,Math.min(max,x));
const cell=worldCell;
const index=gridIndex;
const resourceRate:Stock={food:.65,wood:.60,gold:.50,stone:.45};
export class World {
 effects:Array<Point&{at:number;fire:boolean}>=[];time=0;nextId=1;rng=42;entities:Entity[]=[];shots:Shot[]=[];players:Player[]=[];winner:number|null=null;mode='skirmish';deposited=emptyStock();aiTimer=0;aiLevel:AiLevel='normal';villagerAI:VillagerAI='assist';autoTimer=0;navVersion=0;roadCells=new Set<number>();blocked=new Set<number>();visible=[new Set<number>(),new Set<number>()];explored=[new Set<number>(),new Set<number>()];events:{text:string;kind:string}[]=[];private fogTimer=0;private byId=new Map<number,Entity>();private unitBuckets=new Map<string,Entity[]>();
 constructor(faction:Faction='roman',enemy:Faction='persian',seed=42,mode='skirmish',setup=true){this.rng=seed;this.mode=mode;this.players=[faction,enemy].map(f=>({faction:f,stock:{food:260,wood:220,gold:100,stone:80},era:0,armor:0,tools:0,cart:false,defeat:0,tech:[]}));if(setup)this.setup();}
 random(){this.rng=(Math.imul(1664525,this.rng)+1013904223)>>>0;return this.rng/4294967296;}
 emit(text:string,kind='info'){this.events.push({text,kind});if(this.events.length>30)this.events.shift();}
 add(type:Entity['type'],def:string,owner:Side,x:number,z:number,complete=true){const d=type==='unit'?UNITS[def]:type==='building'?BUILDINGS[def]:null;const hp=d?.hp??100;const e:Entity={id:this.nextId++,type,def,owner,x,z,hp:complete?hp:Math.max(1,hp*.05),maxHp:hp,angle:0,state:'idle',orders:[],cargo:emptyStock(),path:[],pathVersion:-1,timer:0,cooldown:0,progress:complete?1:0,tier:1,queue:[],garrison:[],amount:0,closed:true,lastHit:-99,turn:0};if(owner<2){const p=this.players[owner],u=type==='unit'?UNITS[def]:null;if(type==='building')e.visualEra=p.era;const factor=type==='building'?(p.tech.includes('masonry')?1.15:1):u?(1+p.armor*.12)*(u.mounted&&p.tech.includes('cavalry')||!u.mounted&&!u.siege&&u.role!=='worker'&&p.tech.includes('drill')?1.1:1):1;e.maxHp=hp*factor;e.hp=e.maxHp*(complete?1:.05);}if(type==='unit'&&def==='worker')e.appearance=e.id%2===0?'female':'male';this.entities.push(e);this.byId.set(e.id,e);return e;}
 node(resource:Resource,x:number,z:number,amount:number,def=resource){const e=this.add('resource',def,2,x,z);e.resource=resource;e.amount=amount;e.initialAmount=amount;e.facing=e.id%4;return e;}
 private reindex(){this.byId=new Map(this.entities.map(e=>[e.id,e]));}
 get(id?:number){const e=id===undefined?undefined:this.byId.get(id);return e&&e.hp>0?e:undefined;}
 alive(owner:Side,type?:Entity['type']){return this.entities.filter(e=>e.owner===owner&&e.hp>0&&(!type||e.type===type));}
 setup(){for(const side of [0,1] as const){const sign=side===0?-1:1;const x=sign*52,z=sign*34;const town=this.add('building','town',side,x,z);this.add('building','house',side,x-8,z);this.add('building','barracks',side,x,z-10);this.add('building','lumber',side,x+9,z-4);for(let i=0;i<6;i++){const u=this.add('unit','worker',side,x-4+i*1.5,z+7);u.angle=Math.PI;}this.add('unit','explorer',side,x+6,z+8);this.node('food',x-12,z+9,650);this.node('gold',x+11,z+12,1800);this.node('stone',x-11,z-12,1800);for(let i=0;i<15;i++){const a=i*2.39996,r=2+Math.sqrt(i)*1.8;this.node('wood',x+17+Math.cos(a)*r+(this.random()-.5),z-12+Math.sin(a)*r*.8,180);}town.rally={x:x+7,z:z+8};}
 this.add('building','market',2,0,12);for(let i=0;i<6;i++){this.node(i%2?'gold':'stone',-7+i*3,30,1600);}for(let i=0;i<18;i++){const a=i*2.39996,r=Math.sqrt(i)*2;this.node('wood',-6+Math.cos(a)*r,-22+Math.sin(a)*r*.65,180);}
 if(this.mode==='siege'||this.mode==='imperial'){this.players[0].era=this.mode==='imperial'?3:2;this.players[0].stock={food:1000,wood:1200,gold:900,stone:1100};this.add('building','siege',0,-24,-13);this.add('building','keep',1,20,18);for(let i=0;i<7;i++)this.add('building',i===3?'gate':'wall',1,12+i*2.5,7);for(const [i,id]of ['ram','ram','swordsman','swordsman','archer','archer'].entries())this.add('unit',id,0,-13+i*2,-5);}
 for(const [cx,cz] of [[-48,15],[-46,-48],[0,-46],[48,-12],[47,47],[-14,45]]){for(let i=0;i<24;i++){const angle=this.random()*Math.PI*2,r=Math.sqrt(this.random())*7;this.node('wood',cx+Math.cos(angle)*r,cz+Math.sin(angle)*r,160+Math.floor(this.random()*80));}}
 if(this.mode==='empires')this.setupEmpires();
 for(let cluster=0;cluster<32;cluster++){const cx=-114+this.random()*182,cz=-114+this.random()*228;for(let n=0;n<24;n++){const a=this.random()*Math.PI*2,r=Math.sqrt(this.random())*(5+cluster%5)*(1+.23*Math.sin(a*3+cluster));const axis=cluster*.71,dx=Math.cos(a)*r*1.35,dz=Math.sin(a)*r*.7;const x=cx+dx*Math.cos(axis)-dz*Math.sin(axis),z=cz+dx*Math.sin(axis)+dz*Math.cos(axis);if(!isWater(x+3,z)&&!isCliff(x,z)&&!this.entities.some(e=>e.type==='building'&&dist(e,{x,z})<BUILDINGS[e.def].radius+4)&&!this.entities.some(e=>e.type==='resource'&&dist(e,{x,z})<1.8))this.node('wood',x,z,150+Math.floor(this.random()*120));}}
 for(const [x,z] of [[-86,65],[-5,-83],[45,84],[-102,-55],[53,-60],[-26,91]]){for(let k=0;k<3;k++)this.node(k===0?'stone':'gold',x+k*2.5,z,1600);this.node('food',x-6,z+6,700);}
 this.add('building','market',2,-75,58);this.add('building','market',2,32,-78);
 this.rebuildNav();this.updateFog();if(this.mode==='empires'){for(const side of [0,1] as const){const town=this.alive(side,'building').find(e=>e.def==='town');if(town){const c=cell(town);for(let dz=-28;dz<=28;dz++)for(let dx=-28;dx<=28;dx++){const x=c.x+dx,z=c.z+dz;if(x>=0&&z>=0&&x<GRID_SIZE&&z<GRID_SIZE&&dx*dx+dz*dz<28*28)this.explored[side].add(index(x,z));}}}}this.emit('Settlement ready. Select workers, then right-click a resource.');}
 setupEmpires(){for(const side of [0,1] as const){const sign=side===0?-1:1,x=sign*52,z=sign*34;this.entities=this.entities.filter(e=>e.owner!==side||e.type!=='building'||e.def==='town');this.reindex();this.players[side].era=2;for(const b of this.alive(side,'building'))b.visualEra=2;this.players[side].stock={food:650,wood:900,gold:650,stone:700};
 for(const [def,dx,dz] of [['barracks',-1,-10],['lumber',-21,3],['house',-14,-5],['house',-7,12],['mill',20,16],['market',1,20],['range',9,-14],['stable',-14,-16],['smithy',-10,5],['siege',19,-13],['keep',20,5]] as Array<[string,number,number]>)this.add('building',def,side,x+dx*sign,z+dz*sign);
 for(let i=0;i<4;i++){const farm=this.add('building','farm',side,x+(i%2?12:5)*sign,z+(i<2?12:19)*sign);farm.resource='food';farm.amount=360;farm.initialAmount=360;farm.growth=i===0?.35:i===1?.7:1;}
 for(const [def,dx,dz] of [['mine',25,9],['government',27,-8],['academy',28,4],['healing',24,25]] as Array<[string,number,number]>)this.add('building',def,side,x+dx,z+dz);
 const faction=this.players[side].faction;const infantry=faction==='roman'?'legionary':faction==='persian'?'immortal':'swordsman';const archer=faction==='persian'?'royal-archer':'archer';const horse=faction==='roman'?'equites':faction==='persian'?'cataphract':'light-horse';
 for(let i=0;i<10;i++)this.add('unit',i<5?infantry:i<8?archer:horse,side,x+(5+i%5*1.8)*sign,z+(-4+Math.floor(i/5)*2)*sign);
 for(let i=0;i<8;i++)this.add('unit','worker',side,x+(-5+i)*sign,z+5*sign);
 this.entities=this.entities.filter(e=>e.type!=='resource'||!this.alive(side,'building').some(b=>dist(e,b)<BUILDINGS[b.def].radius+.8));this.reindex();const workers=this.alive(side,'unit').filter(u=>u.def==='worker');workers.forEach((u,i)=>{u.x=x-5+(i%7)*1.5;u.z=z+sign*7+Math.floor(i/7)*1.5;});workers.forEach((u,i)=>{const r:Resource=i<6?'food':i<10?'wood':i<12?'gold':'stone';const node=this.entities.filter(n=>n.resource===r&&n.amount>0).sort((a,b)=>dist(u,a)-dist(u,b))[0];if(node)this.command([u.id],{kind:'gather',target:node.id});});
 }}
 pop(side:Side){const active=this.alive(side,'unit').reduce((a,e)=>a+UNITS[e.def].pop,0);const reserved=this.alive(side,'building').reduce((a,e)=>a+e.queue.filter(q=>q.reserved).reduce((b,q)=>b+UNITS[q.unit].pop,0),0);const cap=Math.min(150,this.alive(side,'building').filter(e=>e.progress>=1).reduce((a,e)=>a+(BUILDINGS[e.def].capacity??0),0));return{active,reserved,cap};}
 afford(side:Side,cost:Cost){return side<2&&Object.entries(cost).every(([k,v])=>this.players[side].stock[k as Resource]>=v!);}
 pay(side:Side,cost:Cost){if(!this.afford(side,cost))return false;for(const[k,v]of Object.entries(cost))this.players[side].stock[k as Resource]-=v!;return true;}
 refund(side:Side,cost:Cost,factor=1){for(const[k,v]of Object.entries(cost))this.players[side].stock[k as Resource]+=v!*factor;}
 available(def:UnitDef,side:Side){return side<2&&this.players[side].era>=def.era&&(!def.factions||def.factions.includes(this.players[side].faction));}
 canTrain(e:Entity,d:UnitDef){return e.type==='building'&&e.progress>=1&&(d.building===e.def||(e.def==='town'&&['worker','explorer','scout'].includes(d.id))||(e.def==='keep'&&d.factions?.includes(this.players[e.owner].faction)))&&this.available(d,e.owner);}
 train(building:Entity,id:string){const d=UNITS[id];if(!d||!this.canTrain(building,d))return false;if(building.queue.length>=12||!this.pay(building.owner,d.cost))return false;building.queue.push({unit:id,progress:0,reserved:false});return true;}
 cancelQueue(e:Entity,i:number){const q=e.queue[i];if(!q)return;this.refund(e.owner,UNITS[q.unit].cost,q.reserved?.8:1);e.queue.splice(i,1);}
 // Ranked block facing the march: melee front, ranged behind, support then siege at the back.
 // Each row is filled left-to-right in the order units already stand, so paths do not cross.
 private formation(ids:number[],target:Point){
  const units=ids.map(id=>this.get(id)).filter((u):u is Entity=>!!u&&u.type==='unit'&&!u.inside);
  const slots=new Map<number,Point>();if(!units.length)return{slots,speed:0};
  const cx=units.reduce((s,u)=>s+u.x,0)/units.length,cz=units.reduce((s,u)=>s+u.z,0)/units.length;
  let fx=target.x-cx,fz=target.z-cz;const len=Math.hypot(fx,fz);if(len<1){fx=Math.sin(units[0].angle);fz=Math.cos(units[0].angle);}else{fx/=len;fz/=len;}
  const rx=fz,rz=-fx,rank=(u:Entity)=>{const d=UNITS[u.def];return d.siege?3:['worker','trader','healer'].includes(d.role)?2:d.range>=6?1:0;};
  const stance=units[0].stance,spacing=Math.max(stance==='spread'?2.8:stance==='testudo'?.9:1.4,...units.map(u=>this.footprint(u)*2+.5));
  const columns=Math.max(1,Math.min(units.length,Math.ceil(Math.sqrt(units.length)*1.6)));
  const rows:Entity[][]=[];
  for(let r=0;r<4;r++){const group=units.filter(u=>rank(u)===r).sort((a,b)=>((b.x-cx)*fx+(b.z-cz)*fz)-((a.x-cx)*fx+(a.z-cz)*fz));for(let i=0;i<group.length;i+=columns)rows.push(group.slice(i,i+columns));}
  rows.forEach((row,r)=>{row.sort((a,b)=>((a.x-cx)*rx+(a.z-cz)*rz)-((b.x-cx)*rx+(b.z-cz)*rz));const back=(r-(rows.length-1)/2)*spacing;row.forEach((u,c)=>{const side=(c-(row.length-1)/2)*spacing;let p={x:target.x+rx*side-fx*back,z:target.z+rz*side-fz*back};if(!this.walkable(p)){let best=Infinity,found=p;for(let ring=1;ring<=4;ring++)for(let k=0;k<8*ring;k++){const a=k*Math.PI*2/(8*ring),q={x:p.x+Math.sin(a)*ring,z:p.z+Math.cos(a)*ring};const s=dist(q,target);if(this.walkable(q)&&s<best){best=s;found=q;}}p=found;}slots.set(u.id,p);});});
  return{slots,speed:Math.min(...units.map(u=>UNITS[u.def].speed))};
 }
 // What a builder does when its site completes and nothing is queued: next foundation nearby, the new field, or the resource the new camp serves.
 private afterBuild(e:Entity,b:Entity):Order|undefined{
  if(isField(b.def))return{kind:'gather',target:b.id};
  if(this.villagerAI==='manual')return undefined;
  const site=this.alive(e.owner,'building').filter(s=>s.progress<1&&s.def!=='road'&&dist(s,e)<18).sort((x,y)=>dist(x,e)-dist(y,e))[0];
  if(site)return{kind:'build',target:site.id};
  const serves:Resource[]=['town','landmark'].includes(b.def)?[]:BUILDINGS[b.def].deposit??[];
  const node=this.entities.filter(n=>n.type==='resource'&&n.hp>0&&n.amount>0&&serves.includes(n.resource!)&&dist(n,b)<14&&this.canSee(e.owner,n)).sort((x,y)=>dist(x,b)-dist(y,b))[0];
  return node?{kind:'gather',target:node.id}:undefined;
 }
 // Resources ordered by how far current gatherers fall short of the wanted split.
 private resourcePriority(side:Side,shares:Stock):Resource[]{
  const n=emptyStock();for(const u of this.alive(side,'unit'))if(u.order?.kind==='gather'&&u.order.resource)n[u.order.resource]++;
  const total=n.food+n.wood+n.gold+n.stone+1;
  return (['food','wood','gold','stone'] as Resource[]).filter(r=>shares[r]>0).sort((a,b)=>(n[a]/total-shares[a])-(n[b]/total-shares[b]));
 }
 // Roles that beat what the human player fields most.
 private counterRoles(){
  const tally:Record<string,number>={};for(const u of this.alive(0,'unit'))tally[UNITS[u.def].role]=(tally[UNITS[u.def].role]??0)+1;
  const n=(...roles:string[])=>roles.reduce((s,r)=>s+(tally[r]??0),0);
  const horse=n('cavalry','heavy-cavalry','camel','mounted-ranged','elephant'),bows=n('ranged','crossbow','skirmisher'),foot=n('infantry','heavy','spear');
  const top=Math.max(horse,bows,foot);if(!top)return[];
  return top===horse?['spear']:top===bows?['cavalry','heavy-cavalry','skirmisher']:['ranged','crossbow','heavy'];
 }
 // Auto villagers (player only): after a few idle seconds take the nearest site, else the scarcest resource nearby.
 private autoVillagers(){
  for(const w of this.alive(0,'unit')){
   if(w.def!=='worker'||w.inside||w.order||w.orders.length||w.state!=='idle'){w.idleSince=undefined;continue;}
   w.idleSince??=this.time;if(this.villagerAI!=='auto'||this.time-w.idleSince<6)continue;
   const site=this.alive(0,'building').filter(b=>b.progress<1&&b.def!=='road'&&dist(b,w)<25).sort((a,b)=>dist(a,w)-dist(b,w))[0];
   if(site){this.command([w.id],{kind:'build',target:site.id});continue;}
   for(const r of this.resourcePriority(0,{food:.45,wood:.35,gold:.15,stone:.05})){const node=this.entities.filter(n=>n.hp>0&&n.amount>0&&n.resource===r&&(n.type==='resource'||n.owner===0)&&dist(n,w)<25&&this.canSee(0,n)).sort((a,b)=>dist(a,w)-dist(b,w))[0];if(node&&this.dropoff(w,r)){this.command([w.id],{kind:'gather',target:node.id});break;}}
   w.idleSince=this.time;
  }
 }
 command(ids:number[],order:Order,append=false){const group=order.point&&ids.length>1&&(order.kind==='move'||order.kind==='attackmove')?this.formation(ids,order.point):undefined;ids.forEach((id,i)=>{const e=this.get(id);if(!e||e.type!=='unit'||e.inside)return;let o=structuredClone(order);if(o.kind==='gather'){const node=this.get(o.target);o.resource??=node?.resource;if(node)o.gatherOrigin??={x:node.x,z:node.z};}if(group?.slots.has(e.id)){o.point=group.slots.get(e.id);o.groupSpeed=group.speed;}else if(o.point&&ids.length>1){const spacing=e.stance==='spread'?2.8:e.stance==='testudo'?.9:1.4;const width=Math.ceil(Math.sqrt(ids.length));o.point={x:o.point.x+(i%width-(width-1)/2)*spacing,z:o.point.z+(Math.floor(i/width)-(Math.ceil(ids.length/width)-1)/2)*spacing};}if(append&&e.order)e.orders.push(o);else{e.order=o;e.orders=[];e.strike=undefined;e.path=[];e.pathGoal=undefined;e.pathEnd=undefined;e.state='idle';e.timer=0;e.tradeLeg=false;e.workSite=undefined;e.workAvoid=undefined;e.workReplans=0;e.workRetryAt=0;}});}
 footprint(e:Entity){return e.type==='building'?BUILDINGS[e.def].radius:e.type==='unit'?(UNITS[e.def].footprint??(UNITS[e.def].siege?1.15:UNITS[e.def].mounted?.65:.4)):.5;}
 validPlacement(id:string,p:Point){return this.canPlace(id,p)&&this.explored[0].has(index(cell(p).x,cell(p).z));}
 private canPlace(id:string,p:Point){const d=BUILDINGS[id];if(!d)return false;const r=d.radius,road=id==='road';if((road?isCliff(p.x,p.z):!flatSite(p.x,p.z,r))||isWater(p.x+r,p.z)||isWater(p.x+r,p.z+r)||isWater(p.x+r,p.z-r))return false;if(Math.abs(p.x)>MAP_HALF-6-r||Math.abs(p.z)>MAP_HALF-6-r)return false;return !this.entities.some(e=>e.hp>0&&(e.type==='building'?(e.def==='road'?road&&dist(e,p)<1.2:dist(e,p)<r+this.footprint(e)+(road||['wall','palisade','gate'].includes(id)&&['wall','palisade','gate'].includes(e.def)?-.001:1)):e.type==='resource'&&e.amount>0&&dist(e,p)<r+.5||e.type==='unit'&&!e.inside&&!isField(id)&&!road&&dist(e,p)<r+this.footprint(e)));}
 build(id:string,p:Point,workers:number[],side:Side=0,facing=0,append=false){const d=BUILDINGS[id];if(!d||side===2||this.players[side].era<d.era||d.factions&&!d.factions.includes(this.players[side].faction)||!this.canPlace(id,p))return null;const cost={...d.cost};if(this.players[side].faction==='castilian'&&['keep','wall','gate','tower'].includes(id)&&cost.stone)cost.stone*=.88;if(!this.pay(side,cost))return null;const b=this.add('building',id,side,p.x,p.z,false);b.state='construction';b.facing=((Math.round(facing)%4)+4)%4;this.command(workers,{kind:'build',target:b.id},append);if(id!=='road')this.rebuildNav();return b;}
 buildRoad(from:Point,to:Point,workers:number[],append=false){const builders=workers.map(id=>this.get(id)).filter((e):e is Entity=>!!e&&e.def==='worker'&&!e.inside&&e.owner===0);if(!builders.length)return 0;const route=[from,...this.path(from,to)],seen=new Set<number>(),assigned=new Set<number>();let count=0;for(const raw of route){if(count>=48)break;const c=cell(raw),i=index(c.x,c.z);if(seen.has(i))continue;seen.add(i);const p={x:c.x*2-MAP_HALF+1,z:c.z*2-MAP_HALF+1};if(!this.validPlacement('road',p))continue;const b=this.build('road',p,[]);if(!b)break;const worker=builders[count%builders.length];this.command([worker.id],{kind:'build',target:b.id},append||assigned.has(worker.id));assigned.add(worker.id);count++;}return count;}
 wallSites(from:Point,to:Point){const xAxis=Math.abs(to.x-from.x)>=Math.abs(to.z-from.z),distance=xAxis?to.x-from.x:to.z-from.z,steps=Math.min(47,Math.floor(Math.abs(distance)/2.2));return Array.from({length:steps+1},(_,i)=>({x:Math.round(from.x)+(xAxis?Math.sign(distance)*i*2.2:0),z:Math.round(from.z)+(xAxis?0:Math.sign(distance)*i*2.2),facing:xAxis?0:1}));}
 existingWall(kind:string,p:Point){return this.entities.some(e=>e.owner===0&&e.hp>0&&e.type==='building'&&e.def===kind&&dist(e,p)<.65);}
 buildWall(kind:string,from:Point,to:Point,workers:number[],append=false){if(!['wall','palisade'].includes(kind))return 0;const builders=workers.map(id=>this.get(id)).filter((e):e is Entity=>!!e&&e.owner===0&&e.def==='worker'&&!e.inside);if(!builders.length)return 0;const assigned=new Set<number>();let count=0;for(const site of this.wallSites(from,to)){if(this.existingWall(kind,site))continue;if(!this.validPlacement(kind,site))break;const b=this.build(kind,site,[],0,site.facing);if(!b)break;const worker=builders[count%builders.length];this.command([worker.id],{kind:'build',target:b.id},append||assigned.has(worker.id));assigned.add(worker.id);count++;}return count;}
 private assignRenovations(side:Side,sites:Entity[]){const workers=this.alive(side,'unit').filter(w=>w.def==='worker'&&!w.inside&&!w.order);if(!workers.length)return;sites.forEach((b,i)=>this.command([workers[i%workers.length].id],{kind:'repair',target:b.id},i>=workers.length));}
 cancelBuilding(b:Entity){if(b.progress>=1)return;this.refund(b.owner,BUILDINGS[b.def].cost,b.progress===0?1:.7*(1-b.progress));b.hp=0;this.rebuildNav();}
 research(b:Entity,id:string){if(b.owner===2||b.progress<1||b.research)return false;const p=this.players[b.owner];let cost:Cost={};
 if(TECHNOLOGIES[id]){const tech=TECHNOLOGIES[id];if(p.tech.includes(id)||b.def!==tech.building||p.era<tech.era||tech.factions&&!tech.factions.includes(p.faction)||tech.requires&&!p.tech.includes(tech.requires)||this.alive(b.owner,'building').some(e=>e.research?.id===id))return false;cost=tech.cost;}
 else if(id==='age'){if(b.def!=='town'||p.era===3||this.alive(b.owner,'building').some(e=>e.research?.id==='age'))return false;const done=this.alive(b.owner,'building').filter(e=>e.progress>=1).map(e=>e.def);const valid=p.era===0?['house','lumber','mine','mill','farm'].filter(x=>done.includes(x)).length>=2:p.era===1?done.includes('smithy')&&['barracks','stable','range'].some(x=>done.includes(x)):done.includes('keep')&&p.armor>=1&&p.tools>=1;if(!valid){if(b.owner===0)this.emit('Age requirements: Feudal needs 2 economic buildings; Castle needs Smithy + military; Imperial needs Keep + armour + tools.');return false;}cost=AGE_COSTS[p.era];}
 else if(id==='armor'){if(b.def!=='smithy'||p.armor>=p.era)return false;cost={food:120,gold:100};}
 else if(id==='tools'){if(!['mill','lumber','mine','academy'].includes(b.def)||p.tools>=2)return false;cost={food:100,wood:80};}
 else if(id==='cart'){if(b.def!=='market'||p.cart)return false;cost={food:120,wood:100};}
 else if(id==='fortify'){if(!['keep','tower','archer-tower','cannon-tower','gate'].includes(b.def)||b.tier>=3||p.era<(b.tier===1?2:3))return false;cost=b.tier===1?{stone:260,gold:120}:{stone:400,gold:240};}
 else return false;if(!this.pay(b.owner,cost))return false;b.research={id,progress:0};if(id==='fortify'){this.assignRenovations(b.owner,[b]);if(b.owner===0)this.emit('Fortification ordered. Villagers must work at the site; use Repair to assign more.');}return true;}
 toggleGate(e:Entity){if(e.def!=='gate')return;e.closed=!e.closed;this.rebuildNav();}
 release(b:Entity){for(const id of [...b.garrison]){const e=this.get(id),p=this.exit(b);if(!e||!p)continue;e.inside=undefined;e.entryPoint=undefined;e.enteredAt=undefined;e.x=p.x;e.z=p.z;e.state='idle';b.garrison=b.garrison.filter(x=>x!==id);}}
 exchange(side:Side,r:Resource,buy:boolean){if(r==='gold')return false;const cost:Cost=buy?{gold:65}:{[r]:50};if(!this.pay(side,cost))return false;this.players[side].stock[buy?r:'gold']+=buy?50:40;return true;}
 rebuildNav(){this.navVersion++;invalidatePathCache(this.blocked);this.blocked.clear();this.roadCells.clear();for(const road of this.entities)if(road.def==='road'&&road.hp>0&&road.progress>=1){const c=cell(road);this.roadCells.add(index(c.x,c.z));}for(let z=0;z<GRID_SIZE;z++)for(let x=0;x<GRID_SIZE;x++)if(isWater(x*2-MAP_HALF+1,z*2-MAP_HALF+1)||isCliff(x*2-MAP_HALF+1,z*2-MAP_HALF+1))this.blocked.add(index(x,z));for(const b of this.entities){if(b.type==='resource'&&b.amount>0&&(b.resource!=='wood'||b.felledAt===undefined)){const c=cell(b);this.blocked.add(index(c.x,c.z));}if(b.type!=='building'||b.hp<=0||isField(b.def)||b.def==='road'||b.def==='gate'&&!b.closed)continue;const c=cell(b),r=BUILDINGS[b.def].radius;for(let x=c.x-4;x<=c.x+4;x++)for(let z=c.z-4;z<=c.z+4;z++)if(x>=0&&z>=0&&x<GRID_SIZE&&z<GRID_SIZE&&Math.abs(x*2-MAP_HALF+1-b.x)<r+.3&&Math.abs(z*2-MAP_HALF+1-b.z)<r+.3)this.blocked.add(index(x,z));}}
 walkable(p:Point){const c=cell(p);return c.x>=1&&c.z>=1&&c.x<GRID_SIZE-1&&c.z<GRID_SIZE-1&&!this.blocked.has(index(c.x,c.z));}
 path(start:Point,goal:Point,radius=0):Point[]{return findPath(start,goal,this.blocked,radius);}
 clearSegment(a:Point,b:Point,radius=.28){const length=dist(a,b),steps=Math.ceil(length/.5);for(let i=1;i<=steps;i++){const p={x:a.x+(b.x-a.x)*i/steps,z:a.z+(b.z-a.z)*i/steps};if(!this.walkable(p)||[-radius,radius].some(dx=>[-radius,radius].some(dz=>!this.walkable({x:p.x+dx,z:p.z+dz}))))return false;}return true;}
 approach(e:Entity,target:Point,distance:number,dt:number){const radial=dist(e,target),ring=radial>0?{x:target.x+(e.x-target.x)/radial*Math.max(.1,distance-.05),z:target.z+(e.z-target.z)/radial*Math.max(.1,distance-.05)}:e;const nearGoal=radial<=distance&&this.walkable(e)&&(dist(e,ring)<.1||this.clearSegment(e,ring,Math.max(.05,this.footprint(e)*.45)));if(nearGoal){e.path=[];e.pathEnd=undefined;e.moveSpeed=0;e.passingOffset=0;e.state='idle';return true;}if((e.order?.kind==='move'||e.order?.kind==='attackmove')&&e.pathEnd&&e.path.length===0&&dist(e,e.pathEnd)<.55){e.order=undefined;e.pathEnd=undefined;e.moveSpeed=0;e.state='idle';return true;}if(!e.pathGoal||dist(e.pathGoal,target)>3||e.pathVersion!==this.navVersion){const delta=dist(e,target);const goal={x:target.x+(e.x-target.x)/delta*Math.max(0,distance-.2),z:target.z+(e.z-target.z)/delta*Math.max(0,distance-.2)};const occupied=e.timer>1?new Set(this.blocked):null;if(occupied)for(const other of this.unitsNear(e,12))if(other.id!==e.id&&other.state!=='walk'&&dist(goal,other)>2){const c=cell(other);occupied.add(index(c.x,c.z));}e.path=occupied?findPath(e,goal,occupied,this.footprint(e)):this.path(e,goal,this.footprint(e));e.pathEnd=e.path.length?{...e.path[e.path.length-1]}:undefined;e.pathGoal={x:target.x,z:target.z};e.pathVersion=this.navVersion;e.timer=0;}
 if(!e.path.length){e.state='blocked';e.timer+=dt;if(e.timer>2){e.pathGoal=undefined;e.timer=0;}return false;}if(e.path.length>1){for(let i=Math.min(7,e.path.length-1);i>0;i--)if(this.clearSegment(e,e.path[i],this.footprint(e)*.8)){e.path.splice(0,i);break;}}while(e.path.length>1&&dist(e,e.path[0])<.22)e.path.shift();const point=e.path[0],d=dist(e,point),u=UNITS[e.def];let speed=u.speed*(e.owner<2&&this.players[e.owner].faction==='steppe'&&u.mounted?1.08:1);if(e.stance==='testudo')speed*=.7;if(e.order?.groupSpeed&&dist(e,target)<20)speed=Math.min(speed,e.order.groupSpeed);const roadCell=cell(e);if(this.roadCells.has(index(roadCell.x,roadCell.z)))speed*=1.18;if(e.owner<2&&this.players[e.owner].tech.includes('royalroad'))speed*=1.08;if(e.owner<2&&this.players[e.owner].cart&&u.role==='worker')speed*=1.08;// Acceleration and a short arrival slowdown avoid instantaneous starts/stops.
 const remaining=Math.max(0,dist(e,target)-distance),turnRate=u.turnRate??(u.mounted?3.5:u.siege?2.2:7);
 const routeAngle=Math.atan2(point.x-e.x,point.z-e.z),heading=e.steeringAngle??e.angle;
 const turn=Math.atan2(Math.sin(routeAngle-heading),Math.cos(routeAngle-heading));
 if(Math.abs(turn)>1.25&&!(u.role==='worker'&&Math.abs(e.passingOffset??0)>1.2)){const angle=heading+clamp(turn,-dt*turnRate,dt*turnRate);e.steeringAngle=angle;e.angle=angle;e.moveSpeed=0;e.state='turn';return false;}
 const desiredSpeed=Math.min(speed,Math.max(.35,Math.sqrt(2*7*remaining)))*(Math.abs(turn)>1.1?.4:1);
 e.moveSpeed=clamp(desiredSpeed,Math.max(0,(e.moveSpeed??0)-dt*9),(e.moveSpeed??0)+dt*(u.mounted?7:10));
 const step=Math.min(e.moveSpeed*dt,d,remaining+.02);
 if(d<.18){e.path.shift();if(!e.path.length&&e.order?.kind==='move'){e.moveSpeed=0;e.state='idle';return true;}if(!e.path.length)e.pathGoal=undefined;return false;}
 const neighbours=this.unitsNear(e,3.5).filter(o=>o.id!==e.id);
 // Allies are soft: a unit may squeeze past friends (separateUnits resolves the overlap); enemies stay solid.
 const clearance=(p:Point)=>neighbours.every(o=>{const full=(this.footprint(o)+this.footprint(e))*1.05,radius=o.owner===e.owner?full*.45:full;const before=dist(o,e),after=dist(o,p);return after>=radius||before<radius&&after>before+.001;});
 let next:Point|undefined,best=Infinity,chosenAngle=heading,chosenOffset=0;
 // Prefer a stable passing side; actual displacement follows the bounded turning direction.
 const side=u.role==='worker'?1:e.id%2?1:-1;
 for(const offset of [0,side*.4,-side*.4,side*.8,-side*.8,side*1.2,-side*1.2,...(u.role==='worker'?[side*1.65,-side*1.65,side*2.2,-side*2.2]:[])]){
  const desired=routeAngle+offset,diff=Math.atan2(Math.sin(desired-heading),Math.cos(desired-heading)),angle=heading+clamp(diff,-dt*turnRate,dt*turnRate);
  const p={x:e.x+Math.sin(angle)*step,z:e.z+Math.cos(angle)*step};
  if(!this.clearSegment(e,p,this.footprint(e)*.8)||!clearance(p))continue;
  const score=dist(p,point)+Math.abs(offset)*.035+Math.abs(offset-(e.passingOffset??0))*.06;
  if(score<best){next=p;best=score;chosenAngle=angle;chosenOffset=offset;}
 }
 if(next){e.angle=chosenAngle;e.steeringAngle=chosenAngle;e.passingOffset=chosenOffset;e.x=next.x;e.z=next.z;e.state='walk';e.timer=0;
  // Idle friends in the way step aside to the side they already stand on.
  const rx=Math.cos(chosenAngle),rz=-Math.sin(chosenAngle);
  for(const o of neighbours){if(o.owner!==e.owner||o.order||o.strike||o.state!=='idle')continue;const full=this.footprint(o)+this.footprint(e)+.1,gap=dist(o,next);if(gap>=full)continue;const s=(o.x-e.x)*rx+(o.z-e.z)*rz>=0?1:-1,push=Math.min(.15,full-gap),q={x:o.x+rx*s*push+Math.sin(chosenAngle)*push*.3,z:o.z+rz*s*push+Math.cos(chosenAngle)*push*.3};if(this.clearSegment(o,q,this.footprint(o)*.8)){o.x=q.x;o.z=q.z;}}
 }
 else{e.passingOffset=u.role==='worker'?side*1.65:e.passingOffset||side*.8;const escape=routeAngle+e.passingOffset,escapeTurn=Math.atan2(Math.sin(escape-heading),Math.cos(escape-heading));e.steeringAngle=heading+clamp(escapeTurn,-dt*turnRate,dt*turnRate);e.angle=e.steeringAngle;e.moveSpeed=0;e.state='blocked';e.timer+=dt;
  // Wedged against a wall or crowd: slide a short step in any free direction that gets closer, or out of an overlap.
  if(e.timer>.4){const r=this.footprint(e)*.8,fits=(q:Point)=>[-r,r].every(dx=>[-r,r].every(dz=>this.walkable({x:q.x+dx,z:q.z+dz})));const wedged=!fits(e);let free:Point|undefined,bestFree=wedged?Infinity:d-.01;for(let k=0;k<12;k++){const a=k*Math.PI/6,q={x:e.x+Math.sin(a)*.15,z:e.z+Math.cos(a)*.15};if(!fits(q)||!clearance(q))continue;const score=dist(q,point);if(score<bestFree){bestFree=score;free=q;}}if(free){e.x=free.x;e.z=free.z;e.state='walk';}}
  if(e.timer>1.2){e.pathGoal=undefined;}}

 return false;}

 exit(b:Entity){const r=BUILDINGS[b.def].radius;for(let i=0;i<24;i++){const a=(b.facing??0)*Math.PI/2+i*Math.PI/12,p={x:b.x+Math.sin(a)*(r+2),z:b.z+Math.cos(a)*(r+2)};if(this.walkable(p)&&!this.entities.some(e=>e.type==='unit'&&e.hp>0&&!e.inside&&dist(e,p)<1.2+this.footprint(e)))return p;}return null;}
 dropoff(e:Entity,r:Resource){const cached=this.get(e.depositTarget);if(cached&&e.depositNavVersion===this.navVersion&&cached.progress>=1&&BUILDINGS[cached.def].deposit?.includes(r))return cached;const target=this.alive(e.owner,'building').filter(b=>b.progress>=1&&BUILDINGS[b.def].deposit?.includes(r)).sort((a,b)=>dist(e,a)-dist(e,b)).find(b=>!!this.findWorkSite(e,b));e.depositTarget=target?.id;e.depositNavVersion=this.navVersion;return target;}
 private findWorkSite(e:Entity,node:Entity){
  const radius=this.footprint(e),field=isField(node.def),reach=node.type==='building'&&!field?BUILDINGS[node.def].radius+1.3:2.65;
  const fits=(p:Point)=>this.walkable(p)&&[-radius,radius].every(dx=>[-radius,radius].every(dz=>this.walkable({x:p.x+dx,z:p.z+dz})));
  const contact=(p:Point)=>{if(node.type!=='resource')return true;const length=dist(p,node),own=cell(node),steps=Math.ceil(length/.3);for(let i=1;i<steps;i++){const q={x:p.x+(node.x-p.x)*i/steps,z:p.z+(node.z-p.z)*i/steps},c=cell(q);if(c.x===own.x&&c.z===own.z)continue;if(!this.walkable(q))return false;}return true;};
  const reserved=this.entities.filter(u=>u.type==='unit'&&u.id!==e.id&&u.hp>0&&!u.inside&&!!u.workSite&&!!u.order&&['gather','build','repair','repairtools'].includes(u.order.kind));
  const points:Point[]=[];
  if(field){const preferred=fieldWorkPoint(node,e.id),r=BUILDINGS[node.def].radius-.35;for(const [dx,dz] of [[0,0],[.9,0],[-.9,0],[0,.9],[0,-.9],[.9,.9],[-.9,-.9]])points.push({x:clamp(preferred.x+dx,node.x-r,node.x+r),z:clamp(preferred.z+dz,node.z-r,node.z+r)});}
  else{if(dist(e,node)<=reach)points.push({x:e.x,z:e.z});const start=Math.atan2(e.x-node.x,e.z-node.z);for(const r of [reach-.8,reach-.4,reach])for(let i=0;i<16;i++){const a=start+i*Math.PI/8;points.push({x:node.x+Math.sin(a)*r,z:node.z+Math.cos(a)*r});}}
  const choices=points.filter(p=>fits(p)&&contact(p)&&(!e.workAvoid||dist(p,e.workAvoid)>.85)&&!reserved.some(u=>dist(p,u.workSite!.point)<radius+this.footprint(u)+.15)).sort((a,b)=>dist(e,a)-dist(e,b)+(field?0:(dist(a,node)-dist(b,node))*1.25));
  for(const point of choices.slice(0,12)){const route=this.clearSegment(e,point,radius)?[point]:this.path(e,point,radius),end=route.at(-1);if(end&&dist(end,point)<.4)return{point,route};}
  return null;
 }
 private approachWork(e:Entity,node:Entity,dt:number):'arrived'|'moving'|'unreachable'{
  let site=e.workSite;
  if(!site||site.target!==node.id||site.version!==this.navVersion||isField(node.def)&&dist(site.point,fieldWorkPoint(node,e.id))>1.5){
   if(site&&site.target!==node.id){e.workAvoid=undefined;e.workReplans=0;}
   const plan=this.findWorkSite(e,node);if(!plan)return'unreachable';
   site=e.workSite={target:node.id,point:plan.point,version:this.navVersion,last:{x:e.x,z:e.z},stalled:0};
   e.path=plan.route;e.pathGoal={...site.point};e.pathEnd={...site.point};e.pathVersion=this.navVersion;e.timer=0;
  }
  const before={x:e.x,z:e.z};
  if(this.approach(e,site.point,.22,dt)){site.stalled=0;e.workReplans=0;e.workAvoid=undefined;return'arrived';}
  // Measure real progress over time, independently of the pathfinder's retry timer.
  const remaining=dist(e,site.point);site.best??=dist(site.last,site.point);if(remaining<site.best-.15){site.stalled=0;site.best=remaining;site.last={x:e.x,z:e.z};}else site.stalled+=dt;
  if(site.stalled>3){e.workAvoid={...site.point};e.workSite=undefined;e.pathGoal=undefined;e.workReplans=(e.workReplans??0)+1;return e.workReplans>=2?'unreachable':'moving';}
  if(dist(e,before)<.0001&&e.state==='walk')e.state='blocked';return'moving';
 }
 private nextResource(e:Entity,failed?:Entity){
  const o=e.order!,resource=o.resource??failed?.resource??'wood',origin=o.gatherOrigin??failed??e;
  o.skipped=(o.skipped??[]).filter(s=>s.until>this.time&&s.id!==failed?.id);if(failed&&failed.amount>0)o.skipped.push({id:failed.id,until:this.time+15});
  const candidates=this.entities.filter(n=>n.hp>0&&n.amount>0&&n.resource===resource&&(n.type==='resource'||n.owner===e.owner)&&dist(n,origin)<30&&!o.skipped!.some(s=>s.id===n.id)&&this.canSee(e.owner,n)).sort((a,b)=>dist(e,a)-dist(e,b));
  e.workSite=undefined;e.workAvoid=undefined;e.workReplans=0;e.path=[];e.pathGoal=undefined;
  for(const node of candidates.slice(0,8)){const plan=this.findWorkSite(e,node);if(!plan){o.skipped.push({id:node.id,until:this.time+15});continue;}o.target=node.id;e.workPhase=0;e.workRetryAt=0;e.workSite={target:node.id,point:plan.point,version:this.navVersion,last:{x:e.x,z:e.z},stalled:0};e.path=plan.route;e.pathGoal={...plan.point};e.pathEnd={...plan.point};e.pathVersion=this.navVersion;e.state='walk';return true;}
  e.workRetryAt=this.time+2;e.state='seeking-resource';return false;
 }
 work(e:Entity,dt:number){const o=e.order!;const carried=(Object.keys(e.cargo) as Resource[]).find(r=>e.cargo[r]>0);const node=this.get(o.target);o.resource??=node?.resource??carried;o.gatherOrigin??=node?{x:node.x,z:node.z}:{x:e.x,z:e.z};if((e.workRetryAt??0)>this.time){e.state='seeking-resource';return;}if(carried&&(e.state==='deposit'||e.cargo[carried]>=(this.players[e.owner].cart?18:12)+(this.players[e.owner].tech.includes('logistics')?4:0)-.001||!node||node.amount<=0||node.resource!==carried)){const b=this.dropoff(e,carried);if(!b){e.state='blocked';return;}const arrival=this.approachWork(e,b,dt);if(arrival==='unreachable'){e.depositTarget=undefined;e.workSite=undefined;e.state='blocked';return;}if(arrival==='arrived'){b.processUntil=this.time+10;b.processed??=emptyStock();b.processed[carried]+=e.cargo[carried];this.players[e.owner].stock[carried]+=e.cargo[carried];if(e.owner===0)this.deposited[carried]+=e.cargo[carried];e.cargo[carried]=0;e.pathGoal=undefined;e.workSite=undefined;e.state='gather';}else e.state='deposit';return;}
 if(node&&isField(node.def)&&node.hp>0&&node.amount<=0){e.state='waiting-seed';return;}
 if(!node||node.amount<=0){this.nextResource(e,node);return;}const arrival=this.approachWork(e,node,dt);if(arrival==='unreachable'){this.nextResource(e,node);return;}if(arrival==='arrived'){e.angle=Math.atan2(node.x-e.x,node.z-e.z);e.state='gather';
 const r=node.resource!,cycle=r==='wood'?1.25:r==='stone'||r==='gold'?1.4:1.3;
 e.workPhase=(e.workPhase??0)+dt;
 if(isField(node.def)&&(node.growth??1)<1){e.state='cultivate';return;}
 if(e.workPhase<cycle)return;e.workPhase%=cycle;node.lastHit=this.time;
 if(r==='wood'&&node.felledAt===undefined){node.fallAngle=Math.atan2(node.x-e.x,node.z-e.z);node.chopProgress=(node.chopProgress??0)+cycle;if(node.chopProgress>=7.5){node.felledAt=this.time;this.rebuildNav();}return;}
 if(r==='wood'&&this.time-(node.felledAt??0)<TREE_FALL_SECONDS)return;
 const cap=(this.players[e.owner].cart?18:12)+(this.players[e.owner].tech.includes('logistics')?4:0);
 e.toolCondition=Math.max(.2,(e.toolCondition??1)-cycle*.0006);let rate=resourceRate[r]*(1+this.players[e.owner].tools*.12)*(.75+.25*e.toolCondition)*(e.owner===1?AI_LEVELS[this.aiLevel].gather:1);if(r==='food'&&this.players[e.owner].faction==='english')rate*=1.08;
 if(this.players[e.owner].tech.includes(r==='food'?'agriculture':r==='wood'?'forestry':'mining'))rate*=1.1;
 const amount=Math.min(node.amount,rate*cycle,cap-e.cargo[r]);node.amount-=amount;e.cargo[r]+=amount;
 if(node.amount<=.001){node.amount=0;node.depletedAt=this.time;if(!isField(node.def))this.rebuildNav();}
 } }

 hit(target:Entity,damage:number){target.hp-=damage;target.lastHit=this.time;if(target.hp<=0){target.hp=0;target.state='dead';target.order=undefined;target.strike=undefined;if(target.type==='building'){target.destroyedAt=this.time;for(const q of target.queue)if(!q.reserved)this.refund(target.owner,UNITS[q.unit].cost);target.queue=[];const occupants=[...target.garrison];this.release(target);for(const id of occupants){const unit=this.get(id);if(unit){unit.hp=Math.max(1,unit.hp*.75);if(unit.inside){unit.inside=undefined;unit.x=target.x;unit.z=target.z;unit.state='idle';}}}target.garrison=[];this.rebuildNav();}if(target.owner===0)this.emit(`${target.type==='unit'?UNITS[target.def].name:BUILDINGS[target.def]?.name??'Entity'} lost.`,'warning');}}
 enemies(e:Entity){return this.entities.filter(t=>t.hp>0&&t.owner<2&&t.owner!==e.owner&&!t.inside&&t.type!=='resource'&&this.canSee(e.owner,t));}
 canSee(side:Side,p:Point){return side===2||this.visible[side].has(index(cell(p).x,cell(p).z));}
 attack(e:Entity,t:Entity,dt:number){const d=UNITS[e.def];const range=d.range+(t.type==='building'?BUILDINGS[t.def].radius:0);if(d.id==='trebuchet'&&dist(e,t)>range){e.turn=0;}if(!this.approach(e,t,range,dt))return;e.angle=Math.atan2(t.x-e.x,t.z-e.z);e.state='recover';if(d.id==='trebuchet'){e.turn+=dt;if(e.turn<6){e.state='deploy';return;}}if(e.cooldown>0)return;if(d.role==='siege'&&dist(e,t)<5){e.state='blocked';return;}e.cooldown=d.cooldown;e.lastAttackAt=this.time;e.state='attack';e.strike={target:t.id,remaining:ATTACK_WINDUP};}
 resolveStrike(e:Entity,t:Entity){const d=UNITS[e.def];if(dist(e,t)>d.range+(t.type==='building'?BUILDINGS[t.def].radius:0)+.7)return;
 let armor=t.type==='unit'?UNITS[t.def].armor+(t.owner<2?this.players[t.owner].armor:0):t.type==='building'?3*t.tier:0;let multiplier=1;const td=t.type==='unit'?UNITS[t.def]:undefined;if(d.role==='spear'&&td?.mounted)multiplier=2.8;if(d.role==='camel'&&td?.mounted)multiplier=1.5;if(d.role==='crossbow'&&td&&td.armor>=3)multiplier=1.7;if(d.role==='skirmisher'&&td?.range&&td.range>3)multiplier=2;if(d.role==='ram')multiplier=t.type==='building'?3:.12;if(t.type==='building'&&!d.siege)multiplier*=.3;if(td?.role==='ram'&&d.range>3)multiplier*=.12;if(td?.shield&&d.range>3&&Math.abs(Math.atan2(Math.sin(Math.atan2(e.x-t.x,e.z-t.z)-t.angle),Math.cos(Math.atan2(e.x-t.x,e.z-t.z)-t.angle)))<Math.PI/3)multiplier*=.65;
 if(t.stance==='testudo'&&d.range>3)multiplier*=.5;if(d.siege&&this.players[e.owner].tech.includes('siegecraft'))multiplier*=1.15;const bowBonus=d.range>3&&!d.siege&&this.players[e.owner].tech.includes('bowcraft')?2:0;const damage=Math.max(1,d.attack+bowBonus+this.players[e.owner].armor*2-armor)*multiplier;if(d.range>3&&d.role!=='ram'){const duration=dist(e,t)/((d.siege?14:25)*(this.players[e.owner].tech.includes('ballistics')?1.25:1));this.shots.push({id:this.nextId++,owner:e.owner,from:{x:e.x,z:e.z},to:{x:t.x,z:t.z},target:t.id,damage,remaining:duration,duration,splash:d.siege?3:0,kind:d.id,launchHeight:d.id==='chariot'?2.8:d.mounted?2.5:d.siege?1.4:1.5,targetHeight:t.type==='unit'?(t.def==='war-elephant'?2.8:UNITS[t.def].mounted?1.8:1):1.5,fire:d.siege&&d.id!=='ballista'&&this.players[e.owner].tech.includes('incendiary')});}else this.hit(t,damage);}
 updateUnit(e:Entity,dt:number){if(e.inside)return;if(!['walk','deposit','blocked'].includes(e.state)){e.moveSpeed=0;e.steeringAngle=e.angle;e.passingOffset=0;}e.cooldown=Math.max(0,e.cooldown-dt);if(e.strike){e.state='attack';const facingTarget=this.get(e.strike.target);if(facingTarget)e.angle=Math.atan2(facingTarget.x-e.x,facingTarget.z-e.z);e.strike.remaining-=dt;if(e.strike.remaining<=1e-7){const target=this.get(e.strike.target);e.strike=undefined;if(target)this.resolveStrike(e,target);}return;}const d=UNITS[e.def];if(!e.order&&e.orders.length)e.order=e.orders.shift();const o=e.order;
 if(d.role==='healer'&&!o){const t=this.alive(e.owner,'unit').find(t=>t.id!==e.id&&t.hp<t.maxHp&&this.time-t.lastHit>=5&&dist(e,t)<6);if(t){t.hp=Math.min(t.maxHp,t.hp+4*dt);e.state='heal';return;}}
 if(o?.kind==='repairtools'&&d.role==='worker'){const forge=this.get(o.target);if(!forge||forge.def!=='smithy'||forge.owner!==e.owner||forge.progress<1){e.order=undefined;return;}if((e.workRetryAt??0)>this.time)return;const arrival=this.approachWork(e,forge,dt);if(arrival!=='arrived'){if(arrival==='unreachable'){e.workRetryAt=this.time+1;e.state='blocked';}return;}e.angle=Math.atan2(forge.x-e.x,forge.z-e.z);e.state='repair-tools';if((e.toolCondition??1)>=.999){e.toolCondition=1;e.order=undefined;e.state='idle';return;}if(this.pay(e.owner,{wood:dt*.25,gold:dt*.1})){e.toolCondition=Math.min(1,(e.toolCondition??1)+dt*.05);forge.processUntil=this.time+3;}return;}
 if(o?.kind==='gather'&&d.role==='worker'){this.work(e,dt);return;}
 if(o?.kind==='build'||o?.kind==='repair'){const b=this.get(o.target);if(d.role!=='worker'||!b||b.type!=='building'||b.owner!==e.owner){e.order=undefined;return;}if((e.workRetryAt??0)>this.time)return;const arrival=this.approachWork(e,b,dt);if(arrival!=='arrived'){if(arrival==='unreachable'){e.workRetryAt=this.time+1;e.state='blocked';
   // Give up on a site that stays unreachable; the AI also cancels its own untouched foundation.
   e.unreachable=(e.unreachable??0)+1;if(e.unreachable>=4){e.unreachable=0;e.order=undefined;e.state='idle';if(e.owner===1&&b.progress===0)this.cancelBuilding(b);if(e.owner===0)this.emit(`Villager cannot reach the ${BUILDINGS[b.def].name} site.`,'warning');}}return;}e.unreachable=0;e.angle=Math.atan2(b.x-e.x,b.z-e.z);e.state='build';if(o.kind==='build'&&b.progress<1){const workers=this.alive(e.owner,'unit').filter(w=>w.order?.target===b.id&&w.state==='build').length;const rate=(1+.6*(Math.min(workers,5)-1))/Math.max(1,workers);b.progress=Math.min(1,b.progress+dt/BUILDINGS[b.def].seconds*rate*(this.players[e.owner].faction==='persian'?1.15:1)*(this.players[e.owner].tech.includes('architecture')?1.15:1));b.hp=Math.max(b.hp,b.maxHp*b.progress);if(b.progress>=1){b.state='idle';b.visualEra=this.players[b.owner].era;if(b.def==='road'){const c=cell(b);this.roadCells.add(index(c.x,c.z));}if(isField(b.def)){b.resource='food';b.amount=b.def==='orchard'?420:360;b.initialAmount=b.amount;b.growth=0;}if(e.owner===0)this.emit(`${BUILDINGS[b.def].name} completed.`);e.order=e.orders.length?undefined:this.afterBuild(e,b);e.pathGoal=undefined;}}
 else if(o.kind==='repair'){if(b.hp<b.maxHp){if(this.pay(e.owner,{wood:dt*.5})){b.hp=Math.min(b.maxHp,b.hp+dt*12);b.workedAt=this.time;}}else if(b.renovation){b.workedAt=this.time;b.renovation.progress=Math.min(1,b.renovation.progress+dt/45);if(b.renovation.progress>=1){b.visualEra=this.players[b.owner].era;b.renovation=undefined;b.state='idle';e.order=undefined;}}else if(b.research?.id==='fortify'){b.workedAt=this.time;b.state='upgrading';}else{e.order=undefined;e.state='idle';}}else{e.order=undefined;e.state='idle';}return;}
 if(o?.kind==='garrison'){const b=this.get(o.target);if(!b||b.type!=='building'||b.owner!==e.owner||b.progress<1||d.mounted||d.siege){e.order=undefined;return;}if(this.approach(e,b,BUILDINGS[b.def].radius+1.4,dt)&&b.garrison.length<(BUILDINGS[b.def].garrison??0)){e.enteredAt=this.time;e.entryPoint={x:e.x,z:e.z};e.inside=b.id;b.garrison.push(e.id);e.order=undefined;e.state='garrison';}return;}
 if(o?.kind==='trade'&&d.role==='trader'){const market=this.get(o.target);const home=this.alive(e.owner,'building').find(b=>b.def==='market'&&b.progress>=1);if(!market||!home)return;const dest=e.tradeLeg?home:market;if(this.approach(e,dest,BUILDINGS[dest.def].radius+1.5,dt)){if(e.tradeLeg){const landmark=this.alive(e.owner,'building').some(b=>b.def==='specialist'&&b.progress>=1)?1.15:1;const income=(8+dist(home,market)*.25)*landmark*(this.players[e.owner].tech.includes('royalroad')?1.2:1)*(this.players[e.owner].faction==='ayyubid'?1.1:1);this.players[e.owner].stock.gold+=income;}e.tradeLeg=!e.tradeLeg;e.pathGoal=undefined;}return;}
 let target=o?.kind==='attack'?this.get(o.target):undefined;if(target&&!this.canSee(e.owner,target))target=undefined;
 if(!target&&d.attack>0&&d.role!=='worker'&&(!o||o.kind==='attackmove'||o.kind==='hold'))target=this.enemies(e).filter(t=>dist(e,t)<(o?.kind==='hold'?d.range+1:14)).sort((a,b)=>dist(e,a)-dist(e,b))[0];if(target){this.attack(e,target,dt);return;}
 if(o?.point&&(o.kind==='move'||o.kind==='attackmove')){if(this.approach(e,o.point,1.1,dt)){e.order=undefined;e.state='idle';}return;}
 if(o?.kind==='attack'&&!target)e.order=undefined;e.state='idle';}
 updateBuilding(b:Entity,dt:number){if(b.progress<1)return;const player=b.owner<2?this.players[b.owner]:null;const q=b.queue[0];if(q&&player){const pop=this.pop(b.owner);if(!q.reserved&&pop.active+pop.reserved+UNITS[q.unit].pop<=pop.cap)q.reserved=true;if(q.reserved){q.progress+=dt/(UNITS[q.unit].seconds*(player.tech.includes('civicservice')?.9:1)*(player.faction==='french'&&UNITS[q.unit].mounted?.9:player.faction==='roman'&&!UNITS[q.unit].mounted&&!UNITS[q.unit].siege&&UNITS[q.unit].attack>0&&UNITS[q.unit].role!=='worker'?.85:1));if(q.progress>=1){const p=this.exit(b);if(p){const u=this.add('unit',q.unit,b.owner,p.x,p.z);if(b.rally)u.order={kind:'move',point:{...b.rally}};b.queue.shift();}}}}
 if(b.research&&player){const r=b.research;const duration=TECHNOLOGIES[r.id]?.seconds??(r.id==='age'?AGE_TIMES[player.era]:r.id==='fortify'?b.tier===1?90:130:45);const crew=r.id==='fortify'?(b.hp>=b.maxHp&&!b.renovation?this.alive(b.owner,'unit').filter(w=>w.state==='build'&&w.order?.kind==='repair'&&w.order.target===b.id&&dist(w,b)<=BUILDINGS[b.def].radius+1.6).length:0):1;r.progress+=dt/duration*(r.id==='fortify'?Math.min(2.5,crew*.7):1);if(r.progress>=1){if(TECHNOLOGIES[r.id]){player.tech.push(r.id);for(const e of this.alive(b.owner)){const u=e.type==='unit'?UNITS[e.def]:null;const affected=r.id==='masonry'&&e.type==='building'||r.id==='cavalry'&&u?.mounted||r.id==='drill'&&u&&!u.mounted&&!u.siege&&u.role!=='worker';if(affected){const ratio=e.hp/e.maxHp;e.maxHp*=r.id==='masonry'?1.15:1.1;e.hp=e.maxHp*ratio;}}}else if(r.id==='age'){const oldEra=player.era;player.era++;const sites=this.alive(b.owner,'building').filter(e=>e.progress>=1&&!isField(e.def)&&e.def!=='road');for(const site of sites){site.visualEra??=oldEra;site.renovation={progress:0};site.state='renovation';}this.assignRenovations(b.owner,sites);if(b.owner===0)this.emit('New age unlocked. Assign villagers with Repair to renovate existing buildings.');}else if(r.id==='armor'){player.armor++;for(const u of this.alive(b.owner,'unit')){const ratio=u.hp/u.maxHp;u.maxHp*=((1+player.armor*.12)/(1+(player.armor-1)*.12));u.hp=u.maxHp*ratio;}}else if(r.id==='tools')player.tools++;else if(r.id==='cart')player.cart=true;else if(r.id==='fortify'){const ratio=b.hp/b.maxHp;b.tier++;b.maxHp*=b.tier===2?1.25:1.2;b.hp=b.maxHp*ratio;b.state='idle';}if(b.owner===0)this.emit(`Research complete: ${r.id}.`);b.research=undefined;}}
 if(isField(b.def)&&b.resource){
  if(b.amount<=0&&(b.def==='orchard'||this.pay(b.owner,{wood:55}))){b.amount=b.def==='orchard'?420:360;b.initialAmount=b.amount;b.growth=0;b.depletedAt=undefined;}
  if(b.amount>0)b.growth=Math.min(1,(b.growth??1)+dt/(b.def==='orchard'?64:42));
 }
 if(b.def==='healing'&&player){for(const u of this.alive(b.owner,'unit'))if(!u.inside&&dist(u,b)<9&&this.time-u.lastHit>5)u.hp=Math.min(u.maxHp,u.hp+dt*(player.tech.includes('medicine')?3:2));}
 const bd=BUILDINGS[b.def];b.cooldown-=dt;if(bd.attack&&b.owner<2&&b.cooldown<=0){const t=this.enemies(b).sort((a,c)=>dist(b,a)-dist(b,c)).find(t=>dist(b,t)<(bd.range??0)+b.tier);if(t){b.cooldown=bd.cooldown??2;b.angle=Math.atan2(t.x-b.x,t.z-b.z);b.lastAttackAt=this.time;const duration=dist(b,t)/(bd.projectile==='cannon'?18:25);this.shots.push({id:this.nextId++,owner:b.owner,from:{x:b.x,z:b.z},to:{x:t.x,z:t.z},target:t.id,damage:Math.max(1,bd.attack+b.garrison.length*2-(t.type==='unit'?UNITS[t.def].armor:6)),remaining:duration,duration,splash:bd.splash??0,kind:bd.projectile??'tower',fire:bd.projectile==='cannon',launchHeight:4,targetHeight:t.type==='unit'?(t.def==='war-elephant'?2.8:UNITS[t.def].mounted?1.8:1):1.5});}}
 }
 updateFog(){for(const side of [0,1] as const){this.visible[side].clear();for(const e of this.alive(side)){if(e.inside||e.type==='resource')continue;const c=cell(e),r=Math.ceil((e.type==='unit'?UNITS[e.def].sight:e.def==='road'?3:BUILDINGS[e.def].sight??20)/2);for(let dx=-r;dx<=r;dx++)for(let dz=-r;dz<=r;dz++){const x=c.x+dx,z=c.z+dz;if(x>=0&&z>=0&&x<GRID_SIZE&&z<GRID_SIZE&&dx*dx+dz*dz<=r*r){this.visible[side].add(index(x,z));this.explored[side].add(index(x,z));}}}}}
 ai(){const side=1,p=this.players[side],units=this.alive(side,'unit'),buildings=this.alive(side,'building').filter(b=>b.progress>=1),town=buildings.find(b=>b.def==='town');if(!town)return;const shares:Stock=p.era===0?{food:.5,wood:.35,gold:.15,stone:0}:{food:.4,wood:.3,gold:.22,stone:.08};
  for(const w of units.filter(u=>u.def==='worker'&&!u.order))for(const r of this.resourcePriority(side,shares)){const node=this.entities.filter(n=>n.hp>0&&n.resource===r&&n.amount>0&&(n.type==='resource'||n.owner===side)&&this.canSee(side,n)).sort((a,b)=>dist(w,a)-dist(w,b))[0];if(node){this.command([w.id],{kind:'gather',target:node.id});break;}}
 const level=AI_LEVELS[this.aiLevel],workerCount=units.filter(u=>u.def==='worker').length,ageUpFirst=this.aiLevel!=='easy'&&this.time>240&&p.era<3&&!town.research&&workerCount>=12&&!!AGE_COSTS[p.era]&&!this.afford(side,AGE_COSTS[p.era]);if(workerCount<level.workers&&town.queue.length<2&&!ageUpFirst)this.train(town,'worker');const pop=this.pop(side);// Farms once wild food near the town runs low: one per two food gatherers, up to ten.
  const wildFood=this.entities.filter(n=>n.type==='resource'&&n.resource==='food'&&n.amount>0&&dist(n,town)<40).length;
  const farms=this.alive(side,'building').filter(b=>b.def==='farm').length,foodCrew=units.filter(u=>u.order?.resource==='food').length;
  const farmNeed=buildings.some(b=>b.def==='mill')&&wildFood<4&&farms<Math.min(10,Math.ceil(foodCrew/2)+1);
  let need=pop.active+pop.reserved>pop.cap-5?'house':!buildings.some(b=>b.def==='mill')?'mill':farmNeed?'farm':p.era>=1&&!buildings.some(b=>b.def==='smithy')?'smithy':p.era>=1&&!buildings.some(b=>b.def==='range')?'range':p.era>=2&&!buildings.some(b=>b.def==='siege')?'siege':p.era>=2&&!buildings.some(b=>b.def==='keep')?'keep':'';
 if(need&&!this.alive(side,'building').some(b=>b.def===need&&b.progress<1)){const worker=units.find(u=>u.def==='worker'&&u.order?.kind!=='build');if(worker){for(let i=0;i<12;i++){const a=this.random()*Math.PI*2,r=(need==='farm'?8:10)+this.random()*(need==='farm'?10:22),spot={x:town.x+Math.sin(a)*r,z:town.z+Math.cos(a)*r};if(!this.canPlace(need,spot))continue;const end=this.path(worker,spot,this.footprint(worker)).at(-1);if(!end||dist(end,spot)>BUILDINGS[need].radius+2)continue;if(this.build(need,spot,[worker.id],side))break;}}}
 if(!town.research)this.research(town,'age');const guard=units.filter(u=>!['worker','trader','healer','scout'].includes(UNITS[u.def].role)).length,ageCost=AGE_COSTS[p.era];
  const saving=this.aiLevel!=='easy'&&p.era<3&&!town.research&&(guard>=4||this.time>240)&&!!ageCost&&!this.afford(side,ageCost);
  for(const b of buildings){if(b.def==='smithy')this.research(b,'armor');if(b.def==='mill')this.research(b,'tools');if(b.queue.length<level.queue&&!saving&&b.def!=='town'){const choices=Object.values(UNITS).filter(d=>d.role!=='worker'&&d.role!=='scout'&&d.role!=='healer'&&d.role!=='trader'&&this.canTrain(b,d));if(choices.length){const counters=this.counterRoles(),picked=this.random()<level.counter?choices.filter(d=>counters.includes(d.role)):[],pool=picked.length?picked:choices;this.train(b,pool[Math.floor(this.random()*pool.length)].id);}}}
 const army=units.filter(u=>!['worker','trader','healer','scout'].includes(UNITS[u.def].role));if(army.length>0&&(army.length>=level.wave||this.mode==='siege')){
  const objectives=[...this.alive(0,'unit').filter(u=>!['worker','trader'].includes(UNITS[u.def].role)&&this.canSee(side,u)),...this.alive(0,'building').filter(b=>this.canSee(side,b))].sort((a,b)=>Math.min(...army.map(u=>dist(u,a)))-Math.min(...army.map(u=>dist(u,b)))).slice(0,8);
  let goal:Entity|Point|null=null,best=-Infinity;
  for(const candidate of objectives.slice(0,4)){const scout=army.reduce((a,b)=>dist(a,candidate)<dist(b,candidate)?a:b);const route=this.path(scout,candidate,this.footprint(scout)),end=route.at(-1);if(!end||dist(end,candidate)>(candidate.type==='building'?BUILDINGS[candidate.def].radius+3:3))continue;const score=100-route.length;if(score>best){best=score;goal=candidate;}}
  goal??={x:-52,z:-34};
  const ready=army.filter(u=>!u.order).map(u=>u.id);if(ready.length)this.command(ready,{kind:'attackmove',point:{x:goal.x,z:goal.z}});
 }}
 private rebuildUnitBuckets(){this.unitBuckets.clear();for(const u of this.entities)if(u.type==='unit'&&u.hp>0&&!u.inside){const key=Math.floor(u.x/4)+','+Math.floor(u.z/4),list=this.unitBuckets.get(key)??[];list.push(u);this.unitBuckets.set(key,list);}}
 private unitsNear(p:Point,radius:number){if(!this.unitBuckets.size)return this.entities.filter(e=>e.type==='unit'&&e.hp>0&&!e.inside&&dist(e,p)<radius);const result:Entity[]=[];const x=Math.floor(p.x/4),z=Math.floor(p.z/4),reach=Math.ceil(radius/4)+1;for(let dx=-reach;dx<=reach;dx++)for(let dz=-reach;dz<=reach;dz++)for(const u of this.unitBuckets.get((x+dx)+','+(z+dz))??[])if(u.hp>0&&!u.inside&&dist(u,p)<radius)result.push(u);return result;}
 private separateUnits(){
 const units=this.entities.filter(e=>e.type==='unit'&&e.hp>0&&!e.inside);this.rebuildUnitBuckets();const buckets=this.unitBuckets;
 for(const u of units){const gx=Math.floor(u.x/4),gz=Math.floor(u.z/4);for(let x=gx-1;x<=gx+1;x++)for(let z=gz-1;z<=gz+1;z++)for(const v of buckets.get(x+','+z)??[]){if(v.id<=u.id)continue;const gap=dist(u,v),minimum=this.footprint(u)+this.footprint(v);if(gap>=minimum)continue;const angle=gap<.001?u.id*2.399:Math.atan2(v.z-u.z,v.x-u.x),push=Math.min(.12,(minimum-gap)*.51),dx=Math.cos(angle)*push,dz=Math.sin(angle)*push;const a={x:u.x-dx,z:u.z-dz},b={x:v.x+dx,z:v.z+dz};if(this.clearSegment(u,a,this.footprint(u)*.8)){u.x=a.x;u.z=a.z;}if(this.clearSegment(v,b,this.footprint(v)*.8)){v.x=b.x;v.z=b.z;}}}
 }
 tick(dt:number){if(this.winner!==null)return;this.time+=dt;this.rebuildUnitBuckets();for(const e of [...this.entities])if(e.hp>0){if(e.type==='unit'&&e.owner<2)this.updateUnit(e,dt);else if(e.type==='building')this.updateBuilding(e,dt);}this.separateUnits();for(const s of this.shots){s.remaining-=dt;if(s.remaining<=0){this.effects.push({x:s.to.x,z:s.to.z,at:this.time,fire:s.fire??false});const t=this.get(s.target);if(s.splash){for(const e of this.entities)if(e.hp>0&&e.type!=='resource'&&!e.inside&&dist(e,s.to)<s.splash)this.hit(e,s.damage*(1-dist(e,s.to)/s.splash*.5));}else if(t&&dist(t,s.to)<2)this.hit(t,s.damage);}}this.shots=this.shots.filter(s=>s.remaining>0);this.effects=this.effects.filter(e=>this.time-e.at<1.2);this.fogTimer+=dt;if(this.fogTimer>=.3){this.updateFog();this.fogTimer=0;}this.aiTimer+=dt;if(this.aiTimer>=AI_LEVELS[this.aiLevel].interval){this.aiTimer=0;this.ai();}this.autoTimer+=dt;if(this.autoTimer>=1){this.autoTimer=0;this.autoVillagers();}for(const side of [0,1] as const){const civic=this.alive(side,'building').some(b=>b.progress>=1&&['town','landmark'].includes(b.def));this.players[side].defeat=civic?0:this.players[side].defeat+dt;if(this.players[side].defeat>=30)this.winner=1-side;}if(this.mode==='provisions'&&this.deposited.food>=400)this.winner=0;if(this.mode==='trade'&&this.players[0].stock.gold>=1000)this.winner=0;}
 snapshot():Snapshot{return structuredClone({version:3,mapSize:MAP_SIZE,time:this.time,nextId:this.nextId,rng:this.rng,players:this.players,entities:this.entities,shots:this.shots,explored:this.explored.map(s=>[...s]),winner:this.winner,mode:this.mode,deposited:this.deposited,aiTimer:this.aiTimer});}
 static restore(s:Snapshot){if(s.version!==3||!Array.isArray(s.entities)||s.entities.length>15000||!Array.isArray(s.players)||s.players.length!==2||!Number.isFinite(s.time))throw Error('Save incompatible or invalid.');for(const e of s.entities){if(!Number.isFinite(e.x)||!Number.isFinite(e.z)||e.type==='unit'&&!UNITS[e.def]||e.type==='building'&&!BUILDINGS[e.def])throw Error('Save contains invalid entities.');}const w=new World(s.players[0].faction,s.players[1].faction,s.rng,s.mode,false);Object.assign(w,structuredClone(s));w.players.forEach(p=>p.tech??=[]);for(const e of w.entities){if(e.type==='building'&&e.owner<2)e.visualEra??=w.players[e.owner].era;if(e.resource)e.initialAmount??=Math.max(1,e.amount);if(e.resource==='wood'&&e.amount<=0)e.felledAt??=-10;if(isField(e.def))e.growth??=1;if(e.type==='unit'&&e.def==='worker')e.appearance??=e.id%2===0?'female':'male';}w.explored=s.explored.map(a=>new Set(s.mapSize===MAP_SIZE?a:a.map(i=>(Math.floor(i/64)+32)*GRID_SIZE+(i%64+32))));w.visible=[new Set<number>(),new Set<number>()];w.events=[];w.reindex();w.rebuildNav();w.updateFog();return w;}
}
